### ISSUE TITLE
Normalize and reset: stop the insanity!

### ISSUE THREAD

**Issue by lyzadanger** [hypothesis/frontend-shared#208]
The time is unfortunately nigh to unravel the different approaches to CSS normalization (making sure browser default quirks are accounted for), CSS reset (actually resetting styles on some or all elements) and element styling (applying styles to HTML elements, without regard for classnames) across our apps.

### The current situation

* Client
  * Normalization: Some c-n-p'ed normalize rules that stretch way back until about [this commit](https://github.com/necolas/normalize.css/blob/master/normalize.css) from a decade ago. There was some rumor that there might be some sort of legacy-technical reason for not using `normalize.css` directly, but in digging back through a lot of git history I didn't see anything too clarifying. These rules are out of date and incomplete compared to `normalize.css` itself.
  * Reset: Extensive, manual. Most block elements have their margins, padding and borders reset. Also sets `box-sizing: border-box` on `*`.
  * Elements: Primarily links (`<a>`) and paragraph (`<p>`) styles; makes all button cursors `pointer`.
* LMS
  * Normalization: `normalize.css` without any customization
  * Reset: None, except CSS generated for _back-end_ use resets `box-sizing: border-box` universally. The front-end CSS does _not_.
  * Elements: none.
* Pattern library/this project
  * Modeled after the client
  * Exported Pattern Library CSS includes its own resets and element styles — baddddd. It should only contain the CSS relevant to styling the `Library.*` components themselves.

### How to eject

I believe LMS is closer to where we want to go, which I'd propose is:

* Rely on `normalize.css`, which is maintained by smart people, for normalization, without being additionally clever
* Pare back resets and/or remove completely. [^1]
* Remove element styles per our CSS authoring standards of using low-specificity class name selectors.
* Break up pattern-library styling such that exported styles only contain true `Library.*` styles

[^1]: I recognize that there are cases where we want certain element-like styles to "apply automatically," a good example being, say, rendered markdown HTML. In this case, we want `<a>` tags to "look like" styled/Hypothesis links. But I would suggest we handle this with a wrapping pattern, e.g. `formattedText` or something, applied to the wrapping/parent element, which could encapsulate some of these styles.

#### Steps

* [x] Replace custom normalization in this package with `normalize.css`. This has no effect on consuming applications, but will help to spot if there is any effect on component styles or pattern styles. This should be fairly easy.
* [x] Remove resets from this package. Like above, this has no effect on consuming applications. Vet patterns to make sure they aren't relying on any resets.
* [x] Replace custom normalization in the `client` with `normalize.css` and test.
* [x] Remove resets from the client. _This will take longer_, as there is a fair amount of assumption baked in to app styles that resets are present. This may need to be done incrementally.
* [x] Refactor elements styles in this package as class-named patterns. I know this will include links and paragraphs. It may also need to include a larger pattern that encapsulates how markdown HTML is formatted.
* [x] Replace element styles in the client with class-named variants and patterns out of this package.
* [x] Split the pattern-library CSS into two: an export that only contains the pattern-library styles themselves (for use in external applications that have an instance of the pattern library) vs. the CSS needed by the pattern-library in _this_ project (which needs the pattern-library styles, but also component and pattern styles).

After that, external applications can set up the template for their instances of the pattern library such that they include:

* The pattern-library CSS: only CSS rules for the Library components themselves
* The app CSS: Such that the pattern library instance is using the same CSS context as the front-end app itself.

That way, we can be sure that the way that patterns appear in the app's pattern library instance _is what they actually look like in the app_.

**Comment by lyzadanger** [comment]
* This package does not assert any resets for its exported components. The pattern-library enables Tailwind's `base` layer, which includes the `preflight` plugin and reset styles, but that is specific to the pattern-library and appropriate.
* The applications (LMS and client) also use Tailwind's `base` layer with `preflight`, so the reset strategy is aligned.
* The few (if any) remaining `base` (i.e. element) styles in the applications are documented.
