### ISSUE TITLE
Epic: Establish patterns for shared icons, Icon component

### ISSUE THREAD

**Issue by lyzadanger** [hypothesis/frontend-shared#229]
This epic tracks the set of tasks needed to migrate to a set of shared icons (in this project's package), as well as a new `Icon` component to replace the `SvgIcon` component.

Why?

* Make this project the source of truth and reference for Hypothesis' icon set. Each of our apps (before this epic's work is done) has their own icon set and source files. These icons have some commonalities, and also some inconsistencies. There's duplication of source. And there's no one place of reference to see or access the entire set. Apps no longer need to maintain their own stables of icon source, but can import what they need from this package.
* A new `Icon` component brings our icon implementation into our convention standards and remediates some challenges with `SvgIcon`. The `SvgIcon` component has a convention mismatch with our naming conventions, so we've been planning to rename it. But there are also some challenges with the way that `SvgIcon` is structured and styled, which has required some hacky CSS workarounds. The new `Icon` component is also in line with our standard component API (e.g. takes standard props).
* Establishing icon patterns in this central, shared place will give us the foundational tools to prototype new, needed patterns that involve icons.

This work includes:

* [x] refactoring how icon registration works to avoid conflicts
* [x] Establishing an `Icon` component to replace `SvgIcon`
* [x] Using shared icons, wherever possible in LMS
* [x] Using shared icons, wherever possible in the client
* [x] Using `Icon` instead of `SvgIcon` in LMS
* [x] Using `Icon` instead of `SvgIcon` in the client
* [x] Deprecating `SvgIcon`
* [ ] Adding an `Icon Component` pattern library page
* [ ] Update `SvgIcon` to `Icon` in the pattern library itself
* [ ] Update `IconButton` to use `Icon` instead of `SvgIcon`
* [ ] Sort out inconsistencies between local and shared icons of the same name (e.g. annotate, sort)
* [ ] Evaluate and/or add utility classes, patterns or mixins for icons.

**Comment by lyzadanger** [comment]
This epic as written is no longer applicable, but some of the tasks have been completed as spec'ed. I'm closing now, and will likely track `Icon`-related needs as a separate ticket/project.
