### ISSUE TITLE
Epic: Re-implement components

### ISSUE THREAD

**Issue by lyzadanger** [hypothesis/frontend-shared#455]
Re-implement existing components or otherwise provide equivalent functionality with updated conventions and API.

This issue serves as a burn-down list.

* [x] `LabeledButton` -> name change to `Button`
* [x] `IconButton`
* [x] `LinkButton`
* [x] ~~`Frame`~~ Use `<Card variant="flat" />` instead
* [x] `Card`
* [x] ~~`Actions`~~ -> will not directly re-implement
* [x] `Scrollbox`
* [ ] `Dialog`
* [x] `Icon`
* [x] `Modal`
* [ ] `ConfirmModal`
* [x] `Checkbox`
* [x] ~~`LabeledCheckbox`~~ (Supported by updated `Checkbox`)
* [x] `TextInput` --> `Input`
* [x] `TextInputWithButton` --> `InputGroup`
* [x] `Link`
* [x] `Panel`
* [x] `Spinner`
* [x] `FullScreenSpinner`
* [x] `Table`
* [x] `Thumbnail`

Notes/tasks:

### Card

* Current styles for `Card` include an `.is-focused` class. This should be changed to an appropriate prop.
* Current styles for `Card` handle for `theme-clean` affordance. This should be done in the `client` instead.
* Default padding for `Card` may be better at `p-3` instead of `p-4`.

### Buttons

* Our shared button component styling asserts cursor styling (pointer). If this is necessary, update the disabled styling to not use a cursor, as it is misleading.
* There are no built-in tailwind variants for aria- attributes, which is how we currently style "active" (pressed, expanded) buttons. We'll need an approach for styling here.

**Comment by lyzadanger** [comment]
At this time, we are not providing an updated `Dialog` or `ConfirmModal` component. No applications were using `Dialog` directly, so it won't be missed. `ConfirmModal` is easily achieved through usage of `Modal`, and has already been adjusted as such in the `client`.
